mainpage/urls.py
from django.urls import path
from . import views


app_name = 'mainpage'
urlpatterns = [
    path('', views.index, name='index'),
]

random_nyamka/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('search/', include('search.urls')),
    path('recipe/', include('recipe.urls')),
    path('recipes/', include('recipes.urls')),
    path('testovaya/', include('testovaya.urls')),
    path('', include('mainpage.urls'))
]

recipe/urls.py
from django.urls import path
from . import views


app_name = 'recipe'
urlpatterns = [
    path('<int:pk>/', views.index, name='dish')
]

recipes/urls.py
from django.urls import path
from . import views


app_name = 'recipes'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:page>/', views.index, name='page')
]

search/urls.py
from django.urls import path
from . import views


app_name = 'search'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index')
]

recipes/models.py
from django.db import models


class Dish(models.Model):
    name = models.CharField(max_length=128, unique=True)
    url = models.URLField()
    standart_portions = models.IntegerField()

    def __str__(self):
        return self.name


class Recipe(models.Model):
    dish = models.ForeignKey('Dish', on_delete=models.CASCADE)
    step = models.CharField(max_length=24)
    action = models.TextField(max_length=500)

    def __str__(self):
        return '{}, шаг № {}'.format(self.dish.name, self.step)


class Type(models.Model):
    L = 'l'
    ML = 'ml'
    KG = 'kg'
    G = 'gram'
    TEASP = 'teasp'
    TABLSP = 'tablsp'
    CUP = 'cup'
    PIECE = 'piece'
    TASTE = 'taste'
    HEAD = 'head'
    JAR = 'jar'
    CHUNK = 'chunk'
    SHEAF = 'sheaf'
    DENTICLE = 'denticle'
    KNIFE = 'knife'
    PINCH = 'pinch'
    STALK = 'stalk'
    type_choices = (
        (L, 'литры'),
        (ML, 'милилитры'),
        (KG, 'килограммы'),
        (STALK, 'стебли'),
        (PINCH, 'щепотки'),
        (KNIFE, 'на кончике ножа'),
        (DENTICLE, 'зубчики'),
        (SHEAF, 'пучки'),
        (CHUNK, 'куски'),
        (JAR, 'банки'),
        (HEAD, 'головки'),
        (TASTE, 'по вкусу'),
        (G, 'граммы'),
        (TEASP, 'чайные ложки'),
        (TABLSP, 'столовые ложки'),
        (CUP, 'стаканы'),
        (PIECE, 'штуки'),
        )

    name = models.CharField(max_length=128, unique=True, choices=type_choices)

    def __str__(self):
        return self.get_name_display()


class Ingredient(models.Model):
    name = models.CharField(max_length=96, unique=True)
    unit_of_mass = models.ForeignKey('Type', on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class IngredientDish(models.Model):
    dish = models.ForeignKey('Dish', on_delete=models.CASCADE)
    ingredient = models.ForeignKey('Ingredient', on_delete=models.CASCADE)
    amount = models.FloatField()

    def __str__(self):
        return '{}, {}'.format(self.dish.name, self.ingredient.name)

mainpage/views.py
from django.shortcuts import render, get_object_or_404
from recipes.models import Dish
import random


def index(request):
    if request.method == 'POST':
        id_list = []
        all_dishes = Dish.objects.values('pk')
        for dish_id in all_dishes:
            id_list.append(dish_id['pk'])
        random_dish_id = random.choice(id_list)
        dish = get_object_or_404(Dish, pk=random_dish_id)
        return render(request, 'mainpage/index.html', {
            'dish': dish
            })
    else:
        return render(request, 'mainpage/index.html')

recipe/views.py
from django.shortcuts import render, get_object_or_404
from recipes.models import Dish


def index(request, pk):
    dish = get_object_or_404(Dish, pk=pk)
    dish_dict = {
        'dish': dish
    }
    return render(request, 'recipe/index.html', dish_dict)

recipes/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from .models import Dish


def index(request, page=1):
    dishes_on_page = 20
    paginator = Paginator(Dish.objects.all(), dishes_on_page)
    last_page = paginator.num_pages
    dishes = paginator.get_page(page)
    template_dict = {
        'page': page,
        'dishes': dishes,
        'last_page': last_page
    }
    return render(request, 'recipes/index.html', template_dict)

search/views.py
from django.shortcuts import get_list_or_404
from django.http import Http404
from django.views import generic
from recipes.models import Dish


class IndexView(generic.ListView):
    template_name = 'search/index.html'
    context_object_name = 'search_result'

    def get_queryset(self):
        if self.request.method == 'GET':
            search_request = self.request.GET.get('search_box')
            if search_request is None:
                raise Http404
            try:
                search_result = get_list_or_404(Dish,
                                                name__icontains=search_request)
            except Http404:
                search_result = 'Not found'
            print(search_request)
            return search_result

mainpage/templates/mainpage/index.html
{% extends 'maintemplates/header.html' %}
{% block content %}
    <div class="container pt-5 pb-5">
        <div class="row justify-content-md-center">
            <div class="col-md-auto">
                <form action="#" method="post">
                    {% csrf_token %}
                    <button class="btn btn-primary btn-lg active"  type="submit">Рандомный рецепт</button>
                </form>
            </div>
        </div>
    </div>
    {% if dish %}
        <div class="container">
            <div class="row justify-content-center"><h1><a href="{{ dish.url }}">{{ dish.name }}</a></h1></div>
            <div class="row justify-content-center"><h5>{{ dish.standart_portions }} порций</h5></div>
            <div class="row justify-content-center">
                <div class="col-4">
                    {% for ingredientdish in dish.ingredientdish_set.all %}
                        <p>{{ ingredientdish.ingredient.name }} - {{ ingredientdish.amount }} {{ ingredientdish.ingredient.unit_of_mass }}</p>
                    {% endfor %}
                </div>
                <div class="col-6">
                    {% for action in dish.recipe_set.all %}
                        <p>{{ action.step }}.  {{ action.action }}</p>
                    {% endfor %}                
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

mainpage/templates/maintemplates/header.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Test</title>
</head> 
<body>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    {% include 'maintemplates/navbar.html' %}
    {% block content %}
    {% endblock %}
</body>
</html>

mainpage/templates/maintemplates/navbar.html
<nav class="navbar navbar-light" style="background-color:lightgreen">
    <a href="{% url 'mainpage:index' %}" class="navbar-brand mb-0 h1">Главная</a>
    <ul class="navbar-nav ml-auto pr-2">
        <li class="nav-item">
            <a href="{% url 'recipes:index' %}" class="nav-link">Рецепты</a>
        </li>
    </ul>
    <form class="form-inline" method="GET" action="{% url 'search:index' %}">
        <input class="form-control mr-sm-2" name="search_box" type="search" placeholder="Рецепт" aria-label="Search">
        <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Найти</button>
    </form>
</nav>

recipe/templates/recipe/index.html
{% extends 'maintemplates/header.html' %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center"><h1><a href="{{ dish.url }}">{{ dish.name }}</a></h1></div>
        <div class="row justify-content-center"><h5>{{ dish.standart_portions }} порций</h5></div>
        <div class="row justify-content-center">
            <div class="col-4">
                {% for ingredientdish in dish.ingredientdish_set.all %}
                    <p>{{ ingredientdish.ingredient.name }} - {{ ingredientdish.amount }} {{ ingredientdish.ingredient.unit_of_mass }}</p>
                {% endfor %}
            </div>
            <div class="col-6">
                {% for action in dish.recipe_set.all %}
                    <p>{{ action.step }}.  {{ action.action }}</p>
                {% endfor %}                
            </div>
        </div>
    </div>
{% endblock %}

recipes/templates/recipes/index.html
{% extends 'maintemplates/header.html' %}
{% block content %}
    <div class="container col-3">
        <span>
            {% for dish in dishes %}
                <p class="text-left"><a href="{% url 'recipe:dish' dish.pk %}">{{ dish.name }}</a></p>
            {% endfor %}
        </span>
    </div>
    {% include 'recipes/pagination.html' %}
{% endblock %}

recipes/templates/recipes/pagination.html
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
    {% if dishes.has_previous %}
      <li class="page-item">
        <a class="page-link" href="{% url 'recipes:page' 1 %}">First</a>
      </li>
      {% if dishes.previous_page_number != 1 %}
        <li class="page-item">
          <a class="page-link" href="{% url 'recipes:page' dishes.previous_page_number %}">Previous</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="{% url 'recipes:page' page|add:'-2' %}">{{ page|add:'-2' }}</a>
        </li>
      {% endif %}
        <li class="page-item">
          <a class="page-link" href="{% url 'recipes:page' page|add:'-1' %}">{{ page|add:'-1' }}</a>
        </li>
    {% endif %}

    <li class="page-item active">
      <p class="page-link">{{ page }}</p>
    </li>

    {% if dishes.has_next %}
      <li class="page-item">
        <a class="page-link" href="{% url 'recipes:page' page|add:'1' %}">{{ page|add:'1' }}</a>
      </li>
      {% if dishes.next_page_number != last_page %}
        <li class="page-item">
          <a class="page-link" href="{% url 'recipes:page' page|add:'2' %}">{{ page|add:'2' }}</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="{% url 'recipes:page' dishes.next_page_number %}">Next</a>
        </li>
      {% endif %}
      <li class="page-item">
        <a class="page-link" href="{% url 'recipes:page' last_page %}">Last</a>
      </li>
    {% endif %}
  </ul>
</nav>

search/templates/search/index.html
{% extends 'maintemplates/header.html' %}
{% block content %}
    <div class="container col-3">
        <span>
            {% for object in search_result %}
                <p><a href="{% url 'recipe:dish' object.pk %}">{{ object.name }}</a></p>
            {% endfor %}
        </span>
    </div>
{% endblock %}